# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal_learningsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('article', 'Artikel'), ('video', 'Video'), ('repo', 'Repository'), ('doc', 'Dokumentation')], default='article', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.goal')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
