# Generated by Django 5.2.17 on 2026-10-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('summary', 'Zusammenfassung'), ('next_steps', 'Naechste Schritte')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to='core.goal')),
            ],
            options={
                'verbose_name': 'KI-Feedback',
                'verbose_name_plural': 'KI-Feedbacks',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
