# Generated by Django 5.2.17 on 2026-10-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aifeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.goal')),
            ],
            options={
                'verbose_name': 'Lernkarte',
                'verbose_name_plural': 'Lernkarten',
                'ordering': ['is_mastered', '-created_at', '-pk'],
            },
        ),
    ]
